---
- hosts: all
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy static site
      copy:
        src: ../index.html
        dest: /var/www/html/index.html
